### ISSUE TITLE
Bug found in SurfGPU.cc for OpenCV3 with no CUDA

### ISSUE THREAD

**Issue by stanathong** [hengli/camodocal#47] opened 2015-12-02 15:58 UTC
My testing environment: OpenCV 3.0 with No CUDA

I believe the bug is more related to OpenCV 3 or else not because CUDA or no CUDA. 

In the function SurfGPU::match, defined in SurfGPU.cc, it calls

m_matcher->knnMatch(dtorsGPU[0], dtorsGPU[1], candidateFwdMatches, 2); 

in which, for OpenCV 3.0 (both Cuda and Non Cuda environment), m_matcher is not defined. This crashed the program. Could you please verify if that is the case and if possible suggest a solution for this please? Thank you very much.

PS. I couldn't built the latest source code from Github so I have to use the previously committed version. Is there any change in make??

**Comment by ahundt** [comment] 2015-12-03 04:01
I'd probably make a separate issue for the compilation problem. When you do, can you post the cmake/make output?

**Comment by ahundt** [comment] 2015-12-03 04:05
For the actual issue, you're saying that no m_matcher object has been created? Perhaps looking at the OpenCV documentation for how to use the object properly, and fixing the bug in the camodocal opencv3 gpu case will fix it?

**Comment by stanathong** [comment] 2015-12-04 10:03
@athundt 
Regarding the make problem, I could try again and post the log on another thread.

@ahundt @hengli 
Regarding the reported problem, I wonder what the environment suits best to run CamOdoCal. I have tried setting up these environments:
   OpenCV 3.0 + No CUDA
   OpenCV 3.0 + CUDA
   OpenCV 2.4.6/2.4.9 + No CUDA
   OpenCV 2.4.11 + CUDA
   (in which No CUDA for me means running the system on a VirtualBox which has no access to GPU)

I found that, for my environment, running CamOdoCal on the enviroment with OpenCV 3.0 + No CUDA could lead me close to the complete process before the program stopped at the point I reported here.

I believe that CamOdoCal works perfectly but I was wondering in which environment setting it could run without the need to make any change to the source code. I can upload my test data set (Images from all the camera in the rigs, Event.dat file and else that is required) if that is helpful. 

I also have a few people who are also struggling running CamOdoCal asking me about running CamOdoCal but I could only answer them upto the points I know. Your answer would be greatly helpful for many people using the package. Thank you very much for your help.

**Comment by ahundt** [comment] 2015-12-04 23:55
Very sorry but more of the right information is needed to help me help you solve your problem. Here is a [guide on how to submit a quality bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#reporting-bugs) some details in the link are specific to that project, but you should be able to get the general idea on what information we need.

Also, I've submitted so many changes because I've been fixing bugs I've encountered myself and I only use a small piece of camodocal at the current time (hand eye calibration). I'm not an original author, that great honor falls to @hengli, whom I appreciate for writing overall very solid software.  

Are you familiar with the process of how to debug software? If not I can try to find a resource with starter instructions for you. It is a valuable skill career wise! Of course either way I'll try to help with whatever I can.

**Comment by stanathong** [comment] 2015-12-05 00:13
@ahundt 
Thanks very much for your effort on this. I do appreciate both you and @hengli and other contributors for making this available as calibrating multi-camera with no overlapping is known a difficult task. And I thank you for always answering my questions.

I'm a novice for Linux and I only started working on this after the need to use CamOdoCal. I found this potential bug by printing out messages to a log file. That's sufficiently enough for me right now to know where the program broke. It was just my query though. Since I believe that the software works perfectly without the need for modification, that's why I ask if there might be a specific environment that works without any tweaking. If that's not the case, I will have to find ways to solve this.

Thank you very much.

**Comment by ahundt** [comment] 2015-12-05 00:19
Yeah it is definitely possible that there is no working environment... I'm very sorry if I broke things, that is entirely possible. I don't have a use case where I can test the entirety of camodocal in these different situations, so I only test the parts I'm able to and know how to take care of. If you're able to fix problems and submit a pull request, or get me the information needed to solve the problem I will definitely help, but I don't currently have the equipment/setup/data to reproduce the problem and debug it myself unless it is specific to hand eye calibration.

**Comment by ahundt** [comment] 2015-12-05 00:29
I'd suggest debugging with no cuda first since it is simpler to step through.

Here are two different approaches for getting started debugging:
- [qt creator + cmake](https://www.youtube.com/watch?v=XFgkk9hBkQc)
- [eclipse + cmake](http://sgpsproject.sourceforge.net/JavierVGomez/index.php/How_to_configure_a_C/C%2B%2B_project_with_Eclipse_and_CMake)

**Comment by ahundt** [comment] 2015-12-05 00:32
Also which linux version are you using? I'm able to successfully compile camodocal with ubuntu 14.04

**Comment by ahundt** [comment] 2015-12-05 00:33
Here is how I set things up: https://github.com/hengli/camodocal/issues/45

**Comment by ahundt** [comment] 2015-12-05 00:34
note those instructions install camodocal as a package, and won't be great for debugging!

**Comment by stanathong** [comment] 2015-12-07 09:44
@ahundt 
Thank you very much for your inputs. I use ubuntu 14.04. Although I don't think debugging will give additional helpful input as I already found out where it broke, I will give this a try and will post an update if I have any. 
Once again thank you very much.

**Comment by ahundt** [comment] 2015-12-10 22:12
@stanathong Could you explain what you meant by m_matcher not being defined though? I'm interested in understanding the problem as well, because looking at the code there seems to be clear lines where the object should be created.

**Comment by supervacuus** [comment] 2015-12-11 17:22
I might be able to help here. We reached the same issue. The `m_match` member in `SurfGPU` is not initialized in the constructor when using OpenCV3, with or without CUDA.

While `SurfGPU.h` provides the correct `MatcherType` for both `HAVE_OPENCV3` `#ifdef`branches, you cannot directly instantiate those types in OpenCV3. This is probably the reason why it was left out and then forgotten during a refactoring.

The matcher-types must now be instantiated with factory functions:

`cv::cuda::DescriptorMatcher::createBFMatcher(cv::NORM_L2)` in case of OpenCV3 + CUDA

and 

`cv::DescriptorMatcher::create("BruteForce")` in case of OpenCV3 without CUDA

Anyway, i am preparing a pull-request that will make it more obvious.

**Comment by stanathong** [comment] 2015-12-11 20:53
@supervacuus 
Thanks very much for the fix. I'll check this out and hopefully I can close this issue by your solution.

@ahundt 
Thanks again for getting back to me and offer to help.

**Comment by ahundt** [comment] 2015-12-12 04:20
Silly me! That was my fault, I forgot it while refactoring. There may be a couple of similar issues lurking elsewhere in the code.

**Comment by stanathong** [comment] 2015-12-12 21:13
I'm going to test the fixed code on my data set and I will report any issues I found during the test. There should be no more issues as this is close to the completion of the process. Thanks very much.

**Comment by stanathong** [comment] 2016-01-04 21:17
Solved by fixed #48.
Shall this thread be closed?

**Comment by ahundt** [comment] 2016-01-05 05:19
Glad it is solved! Closing

**Closed by ahundt** 2016-01-05 05:19 UTC
